// Tabla de Empresas
table empresas {
    id int [pk, increment]
    nombre varchar(255)
    tipo_documento int
    tipo_documento_nombre varchar(255)
    id_pais int [ref: > pais.id] // Relación con tabla de ubicación de países
    documento varchar(255)
    id_responsable int [ref: > empresas_responsables.id] // Relación con responsable
    sucursales int [default: 0]
    region varchar(50)
    zonas int
    zona_horaria varchar(255)
    activo boolean [default: true]
    id_moneda int [ref: > moneda.id] // Relación con la tabla de configuración de moneda
    id_erp int [default: 0]
    id_empresa_erp int
    ccos_obligatorio boolean [default: false]
    vencimiento_cotizacion int [default: 8]
    grupo_empresarial int [default: 1]
    id_subdireccion int
    subdireccion varchar(255)
    id_dir_comercial int
    dir_comercial varchar(255)
    id_dir_operativo int
    dir_operativo varchar(255)
    id_dir_financiero int
    dir_financiero varchar(255)
    id_dir_compras int
    dir_compras varchar(255)
    id_dir_inventario int
    dir_inventario varchar(255)
    correo_compras varchar(255)
    id_moneda_compras int
    simbolo_moneda_compras varchar(20)
    moneda_compras_letras varchar(255)
    id_dir_mantenimiento int
    dir_mantenimiento varchar(255)
    nit_alfanumerico boolean [default: false]
    direccion_principal varchar(255)
    telefono_principal varchar(50)
    reunion_operativa_global boolean [default: false]
    iva_discriminado_cotizaciones boolean [default: true]
    validacion_funcionarios_proveedores boolean [default: true]
    dominio_email varchar(25)
}


table tipos_identificacion {
  id int [pk, increment]
  codigo varchar(10) [unique]  // Ejemplo: 'CC', 'NIT', 'TI', 'CE', 'NUIP'
  descripcion varchar(255)      // Ejemplo: 'Cédula de Ciudadanía', 'NIT', 'Tarjeta de Identidad', 'Cédula de Extranjería', 'Pasaporte'
  pais varchar(100)            // Ejemplo: 'Colombia', 'Perú', 'España'
}


// Tabla de Países (con relación de ubicación)
//relacion de nombre cambia de ubicacion_pais a pais
table pais {
  id int [pk, increment]
  nombre varchar(255)
  continente varchar(255)
  subcontinente varchar(255)
  prefijo int
  iso2 varchar(2)
  iso3 varchar(3)
  time_zone varchar(255) [default: 'America/Bogota']
  impuesto varchar(255)
  id_moneda int [ref: > moneda.id]
}
// Tabla de  de Moneda
// se cambia configuracion_moneda por moneda
//se propone haber todos  los paises inactivos con cioertos datos vacios para que las divisas se manejen aca 
table moneda {
    id int [pk, increment]
    moneda varchar(255) 
    descripcion varchar(255)
    nombre_en_letras varchar(255)
    simbolo varchar(255)
    decimales int [default: 2]
    label varchar(255)
    formato_hora int [default: 1] // 1 -> AM/PM, 2 -> 24h
    idioma varchar(255) 
    predeterminado boolean [default: false]
}

// Tabla de Responsables de Empresas
table empresas_responsables {
    id int [pk, increment]
    nombre varchar(255)
    cargo varchar(255)
    email varchar(255)
    telefono varchar(50)
}

// Tabla de Configuración de Empresa
table empresas_configuracion {
    id int [pk, increment]
    id_empresa int [ref: > empresas.id]
    ccos_obligatorio boolean [default: false]
    reunion_operativa_global boolean [default: false]
    iva_discriminado_cotizaciones boolean [default: true]
    validacion_funcionarios_proveedores boolean [default: true]
}

// Tabla de Sucursales
table empresas_sucursales {
    id int [pk, increment]
    id_empresa int [ref: > empresas.id]
    nombre varchar(255)
    id_responsable int
    responsable varchar(255)
    bodegas int [default: 0]
    activo boolean [default: true]
    saiopen_sucursal varchar(4)
    saiopen_remision varchar(10)
    saiopen_departamento int
    saiopen_ciudad int
    id_erp int [default: 0]
    zona int
    zona_nombre varchar(255)
    reunion_operativa boolean [default: true]
}

// Tabla de empleados_datos_basicos
table empleados_datos_basicos {
    id int [pk, increment]
    id_tipo_identificacion int [ref: > tipos_identificacion.id]//tipo_documento se remplaza ya que estaba funcionando como id para relaccionarla con la tabla de hecho encargada
    //tipo de documentos e extrae de id_tipo_identificacion
    documento varchar(255)
    nombre1 varchar(255)
    nombre2 varchar(255)
    apellido1 varchar(255)
    apellido2 varchar(255)
    nombre varchar(255)
    id_empresa int [ref: > empresas.id]
    empresa varchar(255)
    id_zona int
    zona varchar(255)
    id_sucursal int [ref: > empresas_sucursales.id]
    sucursal varchar(255)
    id_unidad_negocio int
    unidad_negocio varchar(255)
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    id_departamento int
    id_ciudad int
    id_rol int
    rol varchar(255)
    id_cargo int
    cargo varchar(255)
}

// Tabla de empleados_contacto
table empleados_contacto {
    id int [pk, increment]
    id_empleado int [ref: > empleados_datos_basicos.id]
    email_empresa varchar(255)
    email_personal varchar(255)
    direccion varchar(255)
    telefono1 varchar(255)
    telefono2 varchar(255)
    celular1 varchar(255)
    id_celular_empresa int
    celular_empresa varchar(255)
    ciudad_cedula varchar(255)
    eps varchar(255)
    arp varchar(255)
    qrcode mediumblob
    color_menu varchar(11) [default: '0,0,0']
    tipo_fondo varchar(20) [default: 'color_fondo']
    color_fondo varchar(11) [default: '32,124,229']
    imagen_fondo varchar(15)
}

// Tabla de empleados_laborales
table empleados_laborales {
    id int [pk, increment]
    id_empleado int [ref: > empleados_datos_basicos.id]
    username varchar(255)
    password varchar(255)
    password_hash varchar(255)
    salario_base float [default: 566700.00]
    salario float [default: 0.00]
    id_contrato int
    contrato varchar(255)
    ad_contrato blob
    ad_certificado_judicial blob
    ad_cedula blob
    ad_certificado_estudios blob
    ad_hoja_vida blob
    ad_afiliaciones blob
    alerta_actualizacion boolean [default: false]
    activo boolean [default: true]
    estudio_actual varchar(255)
    id_android_device varchar(255)
    tipo_contrato int
    fecha_modificacion datetime
    firma varchar(5000)
    movil_sinc_contactos int [default: 0]
    id_celular varchar(255)
    validar_celular boolean
    valida_hora_ingreso boolean [default: true]
    residente boolean [default: false]
    huella_template blob
    huella_foto blob
    huella_enrola boolean [default: false]
    enturnable boolean [default: false]
    dependencia int
    turno_administrativo boolean [default: false]
    id_turno_administrativo int
    legajo int
    id_nivel_estudio int
    nombre_estudio varchar(255)
    estudia_actualmente boolean [default: false]
}

// Tabla de empleados_documentos
table empleados_documentos {
    id int [pk, increment]
    id_empleado int [ref: > empleados_datos_basicos.id]
    ad_contrato blob
    ad_certificado_judicial blob
    ad_cedula blob
    ad_certificado_estudios blob
    ad_hoja_vida blob
    ad_afiliaciones blob
}

// Tabla de Tipo de Documento
table tipo_documento {
    id int [pk, increment]
    nombre varchar(255)
    detalle varchar(255)
    tipo varchar(255)
    activo int [default: 1]
    codigo_documento int(5)
    id_pais int [ref: > pais.id] // Relación con la tabla de países
}

table terceros_asignados {
  id int [pk, increment]
  id_empresa int [ref: > empresas.id]
  id_tercero int [ref: > terceros.id]
  id_asignado int [ref: > empleados_datos_basicos.id]
  asignado varchar(255)
}

table terceros_bloqueos_log {
  id int [pk, increment]
  id_tercero int [ref: > terceros.id]
  accion varchar(50)
  concepto varchar(50)
  observacion varchar(255)
  id_usuario int [ref: > empleados_datos_basicos.id]
  fecha datetime
}

table terceros_contactos {
  id int [pk, increment]
  id_tercero int [ref: > terceros.id]  // Relación con la tabla `terceros`
  id_tipo_identificacion int [ref: > tipos_identificacion.id]
  identificacion varchar(50) [not null]
  id_tratamiento int [ref: > terceros_tratamiento.id]
  nombre varchar(100) [not null]  // Primer nombre
  segundo_nombre varchar(100)     // Segundo nombre
  apellido varchar(100)           // Primer apellido
  segundo_apellido varchar(100)   // Segundo apellido
  cargo varchar(100)
  direccion varchar(255)
  nacimiento date
  observaciones text  // Cambiado de blob a text
  sexo ENUM('M', 'F', 'Otro')  // Mejor como enum que como varchar
  activo boolean [default: true]
  contacto_auto boolean [default: false]
  id_sucursal int [ref: > empresas_sucursales.id]
  email_principal varchar(255)  // Email principal (por conveniencia)
  informe_encuesta boolean [default: false]  // Cambiado a boolean
  es_principal boolean [default: false]
  indexes {
    (id_tercero, identificacion) [unique]
  }
}

table terceros_contactos_telefonos {
  id int [pk, increment]
  id_contacto int [ref: > terceros_contactos.id] 
  tipo_telefono ENUM('fijo', 'celular', 'fax', 'whatsapp', 'otro') [not null]
  numero varchar(25) [not null]
  extension varchar(10)  // Para extensiones de oficina
  descripcion varchar(100)  // Para notas como "Solo en horario laboral", etc.
  activo boolean [default: true]
  
  indexes {
    (id_contacto, numero) [unique]  // Evitar duplicados
  }
}
table terceros_contactos_email {
  id int [pk, increment]
  id_contacto int [ref: > terceros_contactos.id]
  email varchar(255)
  activo boolean [default: true]
}

//---configuracion proyectos se elimina 

table terceros_ficha_tecnica {
  id int [pk, increment]
  id_tercero int [ref: > terceros.id]
  gran_contribuyente varchar(5)
  responsable_iva varchar(5)
  autoretenedor varchar(5)
  responsable_ica varchar(5)
  cod_actividad_economica varchar(255)
  cod_ciiu varchar(255)
  tarifa_por_mil double(20,2)
  pago_orden varchar(55)
  numero_cuenta varchar(55)
  tipo_cuenta varchar(20)
  entidad varchar(55)
  contacto_pago varchar(255)
  tipo_proveedor varchar(55)
  forma_pago varchar(20)
  desc_pronto_pago varchar(5)
  porc_desc_pronto_pago double(20,2)
  observaciones varchar(255)
  nombre_contacto_cartera varchar(255)
  telefono_contacto_cartera varchar(25)
  extension_contacto_cartera varchar(25)
  email_contacto_cartera varchar(55)
  activo boolean [default: true]
}
table terceros_hotel {
  id int [pk, increment]
  id_tercero int [ref: > terceros.id]
  lugar_evento varchar(250)
  mes_evento varchar(250)
  porcentaje_h int(10)
  porcentaje_p int(10)
  ejecutivo varchar(250)
  fecha date
  salon varchar(250)
  nombre_evento varchar(250)
  nombre_tercero varchar(250)
  servicios_tercero varchar(600)
  valor_cobrar int(20)
  valor_hotel int(20)
  valor_plataforma int(20)
}

table terceros_tipo_documento_confidencial {
  id int [pk, increment]
  nombre varchar(255)
  activo boolean [default: true]
}
table terceros_tratamiento {
  id int [pk, increment]
  nombre varchar(20) //sr. sra, srta. Dr, Dra, Lic, Ing
  activo boolean [default: true]
}

// se borra la tabla direcciones email porque no se sabe muy bien si habia una relacion directa con las direcciones fisicas 
//o simplemente era redundante de contactos email 
// Tabla de Zonas Comerciales de Terceros
table terceros_zona_comercial {
    id int [pk, increment]
    nombre varchar(255)
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    minimo_calificacion double(11, 2)
}

// Tabla de Terceros Tributarios
table terceros_tributario {
    id int [pk, increment]
    nombre varchar(255)
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    activo int [default: 1]
}

// Tabla de Direcciones de Terceros
table terceros_direcciones {
    id int [pk, increment]
    id_tercero int [ref: > terceros.id]
    direccion varchar(255)
    id_departamento int [ref: > ubicacion_departamento.id]
    departamento varchar(255)
    id_ciudad int [ref: > ubicacion_ciudad.id]
    //la ciudad se referencia de id ciudad 
    activo int(2) [default: 1]
    telefono1 varchar(25)
    telefono2 varchar(25)
    celular1 varchar(25)
    celular2 varchar(25)
    nombre varchar(255)
    direccion_principal bool(1) [default: 0] //se paso a boleano 
    encuesta varchar(5) [default: 'false']
    encuesta_destinatario varchar(255)
    encuesta_email varchar(255)
    encuesta_telefono varchar(255)
    encuesta_celular varchar(255)
    id_tipo_cliente_comercial tinyint(2) [default: 1]
    tipo_cliente_comercial varchar(255)
    zona_comercial int(255) 
    id_pais int [ref: > pais.id] // Relación con la tabla de países

    emails int(4)
    id_bodega_siip int(11)
    bodega_siip varchar(255)
    tipo_bodega varchar(255)
    contactos int(4)
  tipo_operacion tinyint(2) [default: 0, note: '''
    0 -> No Aplica
    1 -> Por Contrato
    2 -> Por Demanda
  ''']
  
  envio_formato_ac varchar(5) [default: 'true', note: 'Formato de adiciones y cancelaciones']

}

//se cambia el nombre de configuracion ya que sirve para mas
Table sector_empresarial {
  id int [pk, increment]
  nombre varchar(255) [not null]
  activo int [not null, default: 1]
}


//table terceros_tipo_cliente
table tipos_cliente_comercial {
  id TINYINT [pk] 
  nombre varchar(50) [not null, unique, note: '''
 1|Corporativo         
 2|Centros de Convencio
 3|Clubes              
 4|Division Hoteles    
 5|Unidad Independiente
 7|No Aplica           
  '''] //Deberia manejar prospecto tambien y cambiar el formulario
  descripcion varchar(255)
  activo boolean [default: true]
}

//---- se borra configuracion origen 

// Tabla de Terceros
//  fechas son nuevas, muy buena practica  aunque ya hay otros campos de creacion fecha lo que seria interesante analizar si es diferente
//ocr en el software que extraiga todos esos cammpos
table terceros {
    id int [pk, increment]
     id_tipo_identificacion int [ref: > tipos_identificacion.id]
    //tipo_identificacion se borra ya que se rescata del id tipo_identificacion
    dv varchar(2) // se cambia el tamaño ya que es solo un digito de verificacion
    //tipo se borra ya que se rescata del id tipo_identificacion
    id_tipo_cliente_comercial TINYINT [ref: > tipos_cliente_comercial.id, default: 1]
    //se borra tipo_cliente_comercial varchar(255) porque existe una relacion que maneja esto aunque se debe manejar una limpieza exhaustiva con datos que no concuerdan 
    id_linea_negocio int(11)
    ciudad_identificacion varchar(255)
    numero_identificacion varchar(255) [not null]
    nombre varchar(255)
    nombre_comercial varchar(255)
    cadena_hotelera varchar(250)
    cliente_activo bool(1) //era un int pero debe ser un booleano 
//Se borra el otro cliente activo proque soloe ra una transformacion a si
    fechaInicioContrato date
    fechaFinalContrato date
    direccion varchar(255)
    //se borraron el fax, los 2 telefonos y los 2 celulares porque los va a menajar la tabla contactos 
    //se borra la de email ya que en caso de tener email la tabla que maneja email se consultaria
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    //el pais y el iso2 lo trae del id del pais
    id_departamento int(11) [ref: > ubicacion_departamento.id]
    //el departamento se referencia del id departamento 
    id_ciudad int(11) [ref: > ubicacion_ciudad.id]
    //la ciudad se referencia de id ciudad 
    web varchar(255)
    direcciones int(11)
    contactos int(11)
    nombre_establecimiento varchar(255)
    representante_legal varchar(255)
    id_tipo_identificacion_representante int [ref: > tipos_identificacion.id]
    //se extrae del id informacion para tipo_identificacion_representante
    identificacion_representante varchar(255)
    ciudad_id_representante varchar(255)
    ciudad_representante varchar(255)
    numero_matricula_camara varchar(255)
    libro_camara varchar(255)
    fecha_matricula_camara varchar(255)
    ciudad_camara varchar(255)
    numero_escritura varchar(255)
    fecha_escritura varchar(255)
    notaria_escritura varchar(255)
    ciudad_notaria varchar(255)
    fecha_creacion date
    id_sector_empresarial int [ref: > sector_empresarial.id]
//se extrae del id entonces se borra sector_empresarial
    pagina_web varchar(255)
    //se borra configuracion_origen y el di ya que solo se habian llenado unas contadas veces se borra una tabla relacionada que no tenia relacion
    UserIdLog int(11)
    id_tercero_tributario int(11)
    id_tipo_persona_dian tinyint(1)
    id_forma_pago int(11)
    id_metodo_pago int(11)
    exento_iva varchar(10)
    gravable varchar(10)
    retener_ica varchar(10)
    retener_iva varchar(10)
    agente_retenedor varchar(10)
    clasificacion varchar(1) [default: 'D']
//se elimina id proyecto y proyecto ya que o estan en null o vacios y el id que deberia apuntar a otra tabla es como medio redundante con otras 
    id_actividad int(11)
    actividad varchar(255) [not null]
    tipo_cliente varchar(2) // es un si o un no que radica en si es cliente por lop que es redundante con el campo que ya hace esto 
    tipo_proveedor varchar(2)// es un si que radica si es proveedor 
    // se elimina por ser una duplicacion hecha para un trigger se conserva el booleano asisteH int(11) [default: 0]
    //se eliminan todos los softwares proque nadie los usa
    encuesta varchar(5) [default: 'false']
    encuesta_destinatario varchar(255)
    encuesta_email varchar(255)
    encuesta_celular varchar(255)
    encuesta_telefono varchar(255)
    id_zona_comercial int(11) [ref: < terceros_zona_comercial.id] //se pasa a llamarse id para ser mas descriptivo
    //se extrae de id zona comercial 
    sinc_erp varchar(255) [default: 'false']
//nombres y apellidos se guardan en la tabla contactos
    tercero int(11) [not null,default: '1']
    activo BOOLEAN [default: true] //se cambia tipo de dato 
    ficha_tecnica varchar(10) [default: 'false']
    tarifario varchar(10) [default: 'false']
    usuario_log int(11)
    estado_proveedor bit(1) [default: 1] // Asumiendo que '1' es TRUE
    prioridad_prospecto varchar(5)
    proveedor_subcontratacion varchar(5) [default: 'No']
    correo_subcontratacion varchar(255)
    id_origen_contacto int(11)
    //se elimina origen contacto que se deberia extraer de origen_contacto_terceros
    descripcion_contacto varchar(255)
    tipo_operacion tinyint(4) [default: 0]
    observacion_servicios varchar(255)
    nombre_contacto varchar(255)
    inhabilitado varchar(5) [default: 'false']
    departamento_gestion int(11)
    facturacion_frecuencia int(11)
    facturacion_provision int(11)
    facturacion_provision_detalle varchar(255)
    facturacion_dias int(11)
    facturacion_dia_cierre int(11)
    facturacion_observaciones text
    zip varchar(50)
}


// Tabla de Ubicación de Departamentos
table ubicacion_departamento {
    id int [pk, increment]
    departamento varchar(255)
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    pais varchar(255)
    activo bool(1) [default: 1]
}

// Tabla de Ubicación de Ciudades
table ubicacion_ciudad {
    id int [pk, increment]
    ciudad varchar(255)
    id_pais int [ref: > pais.id] // Relación con la tabla de países
   //el pais se referencia de id pais 
    id_departamento int [ref: > ubicacion_departamento.id] // Relación con la tabla de departamentos
    departamento varchar(255)
    activo int(1) [default: 1]
}


Ref: "empresas"."iva_discriminado_cotizaciones" < "empresas_configuracion"."ccos_obligatorio"

  // Tabla de Pedido Novedades Eventos
table pedido_novedades_eventos {
    id int [pk, increment]
    id_pedido varchar(50)
    consecutivo int
    consecutivo_completo varchar(20)
    observacion longtext
    id_usuario int
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    nombre_usuario varchar(255)
    estado int(1) [default: 0] // 0->abierta, 1->cerrado
    pqrs varchar(5) [default: 'false']
    obs_finalizacion varchar(255)
    fecha_finalizacion datetime
    usuario_finalizacion int
    fecha_novedad datetime
    activo  bit(1) [default: 1] 
}

// Tabla de Documentos Excel Comisiones
table documentos_excel_comisiones {
    id int [pk, increment]
    nombre_formato varchar(255)
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    ext varchar(5)
    randomico varchar(50)
    inicio_vigencia date
    fin_vigencia date
}
// Tabla de Configuración de Horas Extras
table configuracion_horas_extras {
    id int [pk, increment]
    id_pais int [ref: > pais.id] // Relación con la tabla de países
    pais varchar(11)
    ano int(4)
    hed float(11, 2)
    hen float(11, 2)
    hedf float(11, 2)
    henf float(11, 2)
    salario_base float(11, 2)
    inicia_diurno time [default: '06:00:00']
    inicia_nocturno time [default: '22:00:00']
    activo boolean [default: true]
}

// Tabla de tipos de documentos de configuración
table configuracion_documentos_tipo {
  id int [pk, increment]
  nombre varchar(255)
  activo tinyint(1) [default: 1]
  tabla_principal varchar(255)
}

// Tabla de documentos de configuración
table configuracion_documentos {
  id int [pk, increment]
  nombre varchar(255)
  id_tipo int [ref: > configuracion_documentos_tipo.id]
  //se elimina tipo ya que lo trae id_tipo 
  texto longblob
  texto2 longblob
  id_empresa int [ref: > empresas.id]
  //se elimina empresa ya que el id_empresa 
  id_sucursal int [ref: > empresas_sucursales.id]
  //se elimina sucursal ya que se extrae de id_sucursal
}

Ref: "pais"."prefijo" < "pais"."iso2"

Ref: "terceros"."id" < "terceros"."id_ciudad"